### ISSUE TITLE
Concurrency issue waiting to happen in RelayHandler.cs

### ISSUE THREAD

**Issue by okkero** [Elycin/PoolOverSocks5#1]
Multiple threads access and mutate the `minerCount` field, without taking proper synchronization precautions. This is a race condition waiting to happen.

**Comment by Elycin** [comment]
While it is entirely incorrect, I decided to take the lazy approach on this and stick it in places where I was only sure that the minerCount couldn't be improper.

I'll see if I can write some function/list to check the number of active connections.
