### ISSUE TITLE
Possible resource leak in RelayHandler.cs

### ISSUE THREAD

**Issue by okkero** [Elycin/PoolOverSocks5#2]
In the method `HandleClient`: the resources `minerClient`, `poolClient` and `proxyClient` are closed, but not as part of a finally block. Freeing resources should be done either inside a finally block, or automatically with `using` to avoid resource leaks.

**Comment by Elycin** [comment]
Huh,
I was under the impression that when the block exits that any unused variables would be disregarded due to the garbage collector, however being complete and proper doesn't hurt.

**Comment by okkero** [comment]
The garbage collector will collect any C# object that is not referred to in C# code. It can't collect allocated system resources. You have to manage that.
